services:
  # MongoDB Database
  # MongoDB services removed
      - "8080:8080"   # HTTP interface
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - nclip-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB Admin Interface (optional)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: nclip-mongo-admin
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: nclip
      ME_CONFIG_MONGODB_ADMINPASSWORD: secure_password_123
      ME_CONFIG_MONGODB_URL: mongodb://nclip:secure_password_123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - nclip-network

volumes:
  mongodb_data:
    driver: local

networks:
  nclip-network:
    driver: bridge

