services:
  # nclip Application
  nclip:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nclip-app
    restart: unless-stopped
    mem_limit: 128mb
    user: 1001:1001
    read_only: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    environment:
      NCLIP_DATA_DIR: /data
      # Application Configuration
      #NCLIP_URL: https://demo.nclip.app
      NCLIP_PORT: 8080
      NCLIP_TTL: 24h
      NCLIP_BUFFER_SIZE: 5242880 # 5MB
      GIN_MODE: release
    volumes:
      - data:/data
    ports:
      - "8080:8080" # HTTP interface
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
    driver: local
