---
apiVersion: v1
data:
  mongodb-db-name: bmNsaXA=
  mongodb-root-password: c2VjdXJlX3Bhc3N3b3JkXzEyMw==
  mongodb-root-username: bmNsaXA=
kind: Secret
metadata:
  name: mongodb-secret
  namespace: nclip
type: Opaque
