---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nclip
  namespace: nclip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nclip
  template:
    metadata:
      labels:
        app: nclip
    spec:
      containers:
        - name: nclip
          image: ghcr.io/johnwmail/nclip:latest
          ports:
            - containerPort: 8080
          env:
            - name: NCLIP_DATA_DIR
              value: "/data"
            - name: NCLIP_URL
              value: "http://localhost:8080"
            - name: NCLIP_PORT
              value: "8080"
            - name: NCLIP_TTL
              value: "24h"
            - name: NCLIP_BUFFER_SIZE
              value: "5242880" # 5MB
            - name: GIN_MODE
              value: "release"
          volumeMounts:
          - name: data
            mountPath: /data
          - name: tmp
            mountPath: /tmp
          resources:
            limits:
              memory: "128Mi"
              cpu: "80m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            seccompProfile:
              type: RuntimeDefault
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nclip-pvc
        - name: tmp
          emptyDir: {}
