---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nclip
  namespace: nclip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nclip
  template:
    metadata:
      labels:
        app: nclip
    spec:
      containers:
        - name: nclip
          image: ghcr.io/johnwmail/nclip:latest
          ports:
            - containerPort: 8080
          env:
            - name: NCLIP_DATA_DIR
              value: "/data"
            #- name: NCLIP_URL
            #  value: "https://demo.nclip.app"
            - name: NCLIP_PORT
              value: "8080"
            - name: NCLIP_TTL
              value: "24h"
            - name: NCLIP_BUFFER_SIZE
              value: "5242880" # 5MB
            - name: GIN_MODE
              value: "release"
            # Optional: enable upload auth and reference API keys from a Kubernetes Secret
            # - name: NCLIP_UPLOAD_AUTH
            #   value: "true"
            # - name: NCLIP_API_KEYS
            #   valueFrom:
            #     secretKeyRef:
            #       name: nclip-api-keys
            #       key: api-keys
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              memory: "128Mi"
              cpu: "80m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 15
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nclip-pvc
