apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mongodb/secret.yaml
  - mongodb/configmap.yaml
  - mongodb/pvc.yaml
  - mongodb/deployment.yaml
  - mongodb/service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
