version = 0.1

[default]
[default.global.parameters]
stack_name = "nclip-staging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging"
image_repositories = []

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "nclip-staging"
region = "us-east-1"
parameter_overrides = "Environment=staging"

[default.package.parameters]
s3_prefix = "nclip"
region = "us-east-1"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Production environment configuration
[production]
[production.global.parameters]
stack_name = "nclip-production"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=production ExpireDays=30"

[production.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "nclip-production"
region = "us-east-1"
parameter_overrides = "Environment=production ExpireDays=30"
