name: Integration Test

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

env:
  GO_VERSION_LATEST: "1.25"

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.event_name == 'pull_request'

    strategy:
      matrix:
        go-version: ["1.23", "1.24", "1.25"]
        upload-auth: ["true", "false"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-

      - name: Download dependencies
        run: go mod download

      - name: Build nclip binary
        env:
          CGO_ENABLED: 0
        run: |
          VERSION="test-${GITHUB_SHA:0:7}"
          go build -v \
            -ldflags="-s -w -X main.version=${VERSION} -X main.buildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ) -X main.gitCommit=${GITHUB_SHA:0:7}" \
            -o nclip \
            .
          chmod +x nclip

      - name: Start nclip server (filesystem backend)
        env:
          NCLIP_PORT: 8080
          NCLIP_DATA_DIR: ./testdata
          GIN_MODE: release
        run: |
          mkdir -p ./testdata
          echo "Starting nclip server (filesystem backend only)..."
          # When upload-auth is true, the job should set API keys so tests can auth
          if [ "${{ matrix.upload-auth }}" = "true" ]; then
            TEST_KEY=$(openssl rand -hex 12)
            echo "NCLIP_UPLOAD_AUTH=true" >> $GITHUB_ENV
            echo "NCLIP_API_KEYS=$TEST_KEY" >> $GITHUB_ENV
            echo "NCLIP_TEST_API_KEY=$TEST_KEY" >> $GITHUB_ENV
            export NCLIP_UPLOAD_AUTH=true
            export NCLIP_API_KEYS=$TEST_KEY
            export NCLIP_TEST_API_KEY=$TEST_KEY
            echo "Generated test API key for upload auth"
          else
            echo "NCLIP_UPLOAD_AUTH=false" >> $GITHUB_ENV
            export NCLIP_UPLOAD_AUTH=false
          fi
          ./nclip &
          NCLIP_PID=$!
          echo "NCLIP_PID=$NCLIP_PID" >> $GITHUB_ENV
          echo "nclip started with PID: $NCLIP_PID"

      - name: Run integration tests
        env:
          NCLIP_URL: http://localhost:8080
          NCLIP_UPLOAD_AUTH: ${{ matrix.upload-auth }}
        run: |
          echo "Running integration tests (upload-auth=${{ matrix.upload-auth }})..."
          # Export any NCLIP_* values injected into the environment by the previous step
          if [ -n "${NCLIP_API_KEYS:-}" ]; then export NCLIP_API_KEYS="$NCLIP_API_KEYS"; fi
          if [ -n "${NCLIP_TEST_API_KEY:-}" ]; then export NCLIP_TEST_API_KEY="$NCLIP_TEST_API_KEY"; fi
          bash scripts/integration-test.sh

      - name: Stop nclip server
        if: always()
        run: |
          if [ -n "${NCLIP_PID:-}" ]; then
            echo "Stopping nclip server (PID: $NCLIP_PID)"
            kill $NCLIP_PID || true
            sleep 2
            kill -9 $NCLIP_PID 2>/dev/null || true
          fi

      - name: Upload integration test artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-artifacts-${{ matrix.go-version }}-run${{ github.run_id }}
          path: |
            nclip
            scripts/
          retention-days: 7
